docs: add getting started w/development guide
kubernetes-sigs/cri-tools pull request #667
Opened 2020-09-24 21:11 UTC by adams0619

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

2020-09-24 21:24 UTC, adams0619 commented
/kind documentation

2020-09-25 06:56 UTC, saschagrunert reviewed
Hey, thank you for the contribution :pray: 

May I ask you to sign the CNCF CLA first?

2020-09-30 17:34 UTC, hickeyma requested changes
@adams0619 Thank you for adding this helpful documentation. I have some feedback provided inline and it is mostly to just simplify the doc by referencing other docs.

2020-09-30 17:34 UTC, hickeyma commented on docs/developer-guide.md
> +  _Background for why this is necessary: `docker` makes use of `containerd`, but when installed it has `cri` disabled, the updated config enables `cri` and allows `docker` to make use of the developm
I think this is very valuable information on using containerd/cri. I feel however that it should reside in [containerd/cri dev guide](https://github.com/containerd/cri#getting-started-for-developers). Do you mind opening a PR there and updating its guide where necessary.

I feel in here it should just contain:

Follow the [containerd/cri dev guide](https://github.com/containerd/cri#getting-started-for-developers) to make and install containerd/cri runtime.

2020-09-30 17:34 UTC, hickeyma commented on docs/developer-guide.md
> +
Remove

2020-09-30 17:34 UTC, hickeyma commented on docs/developer-guide.md
> +- Clone / Fork repo into `$HOME/go/src/github.com/kubernetes-sigs/cri-tools`
You would assume that someone has the repo by now, so not needed

2020-09-30 17:34 UTC, hickeyma commented on docs/developer-guide.md
> +Running `cri-tools` is very similar to the steps followed above
I think this could be condensed down into:

Build and install `cri-tools` as follows:

2020-10-04 12:34 UTC, dougsland reviewed
I would suggest squash the two patches.

2020-10-07 20:25 UTC, adams0619 commented
@saschagrunert Not sure why the following check is failing for my PR `cri-test`, don't think my changes should have any effect there... any help would be appreciated.

Error:
```
Summarizing 6 Failures:

[Fail] [k8s.io] Streaming runtime should support streaming interfaces [It] runtime should support portforward in host network 
/home/runner/work/cri-tools/cri-tools/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/networking.go:253

[Fail] [k8s.io] Streaming runtime should support streaming interfaces [It] runtime should support portforward in host network 
/home/runner/work/cri-tools/cri-tools/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/networking.go:253

[Fail] [k8s.io] Streaming runtime should support streaming interfaces [It] runtime should support portforward [Conformance] 
/home/runner/work/cri-tools/cri-tools/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/networking.go:253

[Fail] [k8s.io] Streaming runtime should support streaming interfaces [It] runtime should support portforward in host network 
/home/runner/work/cri-tools/cri-tools/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/networking.go:253

[Fail] [k8s.io] Streaming runtime should support streaming interfaces [It] runtime should support portforward [Conformance] 
/home/runner/work/cri-tools/cri-tools/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/networking.go:253

[Fail] [k8s.io] Streaming runtime should support streaming interfaces [It] runtime should support portforward [Conformance] 
/home/runner/work/cri-tools/cri-tools/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/networking.go:253

Ran 75 of 83 Specs in 335.644 seconds
FAIL! -- 73 Passed | 2 Failed | 0 Flaked | 0 Pending | 8 Skipped


Ginkgo ran 1 suite in 5m35.67118475s
Test Suite Failed
--- FAIL: TestCRISuite (335.68s)
Error:     cri_test.go:126: critest path: /usr/local/bin/critest
Error:     cri_test.go:161: Failed to run tests in parallel: exit status 1
FAIL
Error: Process completed with exit code 1.
```

2020-10-08 07:18 UTC, saschagrunert commented on docs/developer-guide.md
> +- [Docker](https://docs.docker.com/get-docker/)
For which part do we need Docker? I doubt that we require it.

2020-10-08 07:18 UTC, saschagrunert commented on docs/developer-guide.md
> +`cri-tools` need the following programs installed in a system in order to work correctly:
I would rephrase it to mention that we need those for development only.

2020-10-08 07:18 UTC, saschagrunert commented on docs/developer-guide.md
> +This guide will use `containerd/cri` as the container runtime. You may use `cri-o` instead but you may need some additional steps to ensure it works. You can also follow the `cri-o` [install guide](h
```suggestion
This guide will use `containerd/cri` as the container runtime. You may use CRI-O instead but you may need some additional steps to ensure it works. You can also follow the CRI-O [install guide](https://github.com/cri-o/cri-o/blob/master/install.md#install-packaged-versions-of-cri-o) if you prefer to use the packaged version.
```

2020-10-08 07:18 UTC, saschagrunert commented
Yes the test failures are not coming from this patch, I'll check what's going on.

2020-10-08 08:18 UTC, saschagrunert commented
Looks like a flake, not it's working :)

2020-10-14 11:05 UTC, hickeyma requested changes

2020-10-14 11:05 UTC, hickeyma commented on docs/developer-guide.md
> +If you followed the guide so far you may likely already have `containerd` installed, but we will need to install the latest development version.
If you followed the guide so far you may likely already have `containerd` installed, but we will need to install the latest development version. --> You will require the latest development version of `containerd`.

2020-10-14 11:05 UTC, hickeyma commented on docs/developer-guide.md
> +Running the development versions of `containerd` is not required if you do not plan on developing for `crictl`, `containerd` or `kubernetes`, you can instead install the latest packaged version for y
Not sure this sentence is needed as it seems to conflict with the previous sentence?

2020-10-14 11:05 UTC, hickeyma commented on docs/developer-guide.md
> +- Follow the [`containerd/cri` dev guide](https://github.com/containerd/cri#getting-started-for-developers) to `make` and install `containerd/cri` runtime.
install --> install the

2020-10-14 11:05 UTC, hickeyma commented on docs/developer-guide.md
> +You can build and install `cri-tools` following the steps below:
You can build and install `cri-tools` following the steps below: --> You can build and install `cri-tools` as follows:

2020-10-14 11:05 UTC, hickeyma commented on docs/developer-guide.md
> +- Install necessary build tools using `make` within the repo directory
Install necessary build tools using `make` within the repo directory --> Install the dependencies:

2020-10-14 11:05 UTC, hickeyma commented on docs/developer-guide.md
> +- Build `cri-tools` from source and install its binary using `make`
Build `cri-tools` from source and install its binary using `make` --> Build `cri-tools` (`critest` and `crictl`) and install to common location:

2020-10-14 11:07 UTC, hickeyma commented
Thanks for updating @adams0619. Nearly there, just some more comments inline.

2020-10-22 00:18 UTC, adams0619 commented
@hickeyma @saschagrunert Updated to address comments... could I get another review on this?

2020-10-22 07:05 UTC, saschagrunert approved these changes
Just a nit, otherwise LGTM
/approve

2020-10-22 07:05 UTC, saschagrunert commented on docs/developer-guide.md
> +The latest development version of `containerd` is required.
```suggestion
The latest development version of `containerd` or CRI-O is required.
```

2020-10-22 08:14 UTC, hickeyma approved these changes
2 small nits, otherwise LGTM.

2020-10-22 08:14 UTC, hickeyma commented on docs/developer-guide.md
> +Running the development versions of `containerd` is not required if you do not plan on developing for `containerd` or `kubernetes`, you can instead install the latest packaged version for your given
Remove as this is confusing with the sentence before it.

2020-10-22 08:14 UTC, hickeyma commented on docs/developer-guide.md
> +- Follow the [`containerd/cri` dev guide](https://github.com/containerd/cri#getting-started-for-developers) to `make` and install the `containerd/cri` runtime.
Remove `-` because it should not be bulleted.

2020-11-02 15:17 UTC, hickeyma approved these changes
LGTM, thanks for your effort on this @adams0619

2020-11-02 16:20 UTC, saschagrunert approved these changes
/lgtm

2020-11-02 16:20 UTC, saschagrunert commented
/approve

2020-11-02 16:20 UTC, merged