fix FinishedAt of the container status
kubernetes-sigs/cri-tools pull request #724
Opened 2021-03-01 12:26 UTC by Iceber

Signed-off-by: Iceber Gu <wei.cai-nat@daocloud.io>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Finished time is always `1754-08-31T06:49:24.128654848+08:05` in the run and create states, because `FinishedAt` is `-6795364578871345152`
```sh
[root@iceber-3 ~]# crictl inspect 587444fc34ec9
{
  "status": {
    "id": "587444fc34ec9846c163d0c74bbf985ac73662817a89e16b7328b955a03ef902",
    "metadata": {
      "attempt": 6,
      "name": "dx-arch-stolon-sentinel"
    },
    "state": "CONTAINER_RUNNING",
    "createdAt": "2021-03-01T16:45:23.390180141+08:00",
    "startedAt": "2021-03-01T16:45:23.544299436+08:00",
    "finishedAt": "1754-08-31T06:49:24.128654848+08:05",
    "exitCode": 0,
```
#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:
Fixed output in the running state:
```sh
[root@caiwei-3 ~]# ./crictl inspect 587444fc34ec9
{
  "status": {
    "id": "587444fc34ec9846c163d0c74bbf985ac73662817a89e16b7328b955a03ef902",
    "metadata": {
      "attempt": 6,
      "name": "dx-arch-stolon-sentinel"
    },
    "state": "CONTAINER_RUNNING",
    "createdAt": "2021-03-01T16:45:23.390180141+08:00",
    "startedAt": "2021-03-01T16:45:23.544299436+08:00",
    "finishedAt": "",
    "exitCode": 0,
```

#### Does this PR introduce a user-facing change?

2021-03-02 13:59 UTC, saschagrunert requested changes

2021-03-02 13:59 UTC, saschagrunert commented on cmd/crictl/container.go
> +		jsonMap["startedAt"] = time.Unix(0, cs.FinishedAt).Format(time.RFC3339Nano)
```suggestion
		jsonMap["startedAt"] = time.Unix(0, cs.StartedAt).Format(time.RFC3339Nano)
```

2021-03-02 14:02 UTC, saschagrunert reviewed
Which container runtime did you use for the tests? I did a local test with CRI-O (master) and the resulting dates for a created container were:

```json
"startedAt": "1970-01-01T01:00:00+01:00",
"finishedAt": "1970-01-01T01:00:00+01:00",
```

I think we're good to move forward with that change. We could say that it's a breaking change but I would not expect someone to rely on the date parsing output if the container state does not match.

2021-03-02 14:31 UTC, Iceber commented
> Which container runtime did you use for the tests? I did a local test with CRI-O (master) and the resulting dates for a created container were:
> 
> ```json
> "startedAt": "1970-01-01T01:00:00+01:00",
> "finishedAt": "1970-01-01T01:00:00+01:00",
> ```
> 
> I think we're good to move forward with that change. We could say that it's a breaking change but I would not expect someone to rely on the date parsing output if the container state does not match.

I did the tests with the `dockershim`.
You get the `1970-01-01T01:00:00+01:00` because the started and finished timestamp is 0 (zero value)
https://github.com/cri-o/cri-o/blob/6ee8d68771c24a045aef1f5372eae377928a3530/server/container_status.go#L68-L84

You can use --debug to see the returned data

2021-03-02 14:40 UTC, Iceber commented
And kubernetes sometimes ignores startedAt and finishedAt when dealing with `CRI container status`, as seen [here](https://github.com/kubernetes/kubernetes/blob/793390e13be91d79150b57abad5710477ab96bd7/pkg/kubelet/kuberuntime/kuberuntime_container.go#L510-L522)

2021-03-02 16:33 UTC, saschagrunert commented
> And kubernetes sometimes ignores startedAt and finishedAt when dealing with `CRI container status`, as seen [here](https://github.com/kubernetes/kubernetes/blob/793390e13be91d79150b57abad5710477ab96bd7/pkg/kubelet/kuberuntime/kuberuntime_container.go#L510-L522)
> 
> I'm thinking about whether to show `""` or `0001-01-01T00:00:00Z`(`time.Time{}.Format(time.RFC3339Nano)`) for empty `startedAt` and `finishedAt`
> `0001-01-01T00:00:00Z` has the advantage that it can be parsed by `time.Parse` without returning errors. And `result.IsZero()` is true

In that case it would't be a "breaking change". I like that. :+1:

2021-03-03 02:26 UTC, Iceber commented
@saschagrunert  update to show `0001-01-01T00:00:00Z`.
PTAL, Thanks

2021-03-03 12:53 UTC, saschagrunert approved these changes
/lgtm
/hold for the tests

2021-03-03 12:54 UTC, saschagrunert commented
/hold cancel

the CI failures are not related to this change, I'll follow-up on those.

2021-03-04 09:33 UTC, saschagrunert approved these changes
/lgtm

2021-03-04 09:56 UTC, merged